[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Supplier API"
authors = [{name = "Lal Kumar Rai", email = "abc@gmail.com"}]
dynamic = ["version", "description"]
